#!/usr/bin/perl -I /root/tgmanage
use strict;

BEGIN {
        require "include/config.pm";
        eval {
                require "include/config.local.pm";
        };
}

my $bind_base = "/etc/bind/";
my $dhcpd_base = "/etc/dhcp/";

my $shellconf_file = "include/tgmanage.cfg.sh";

open CFG, ">" . $shellconf_file or die ($! . " " . $shellconf_file );

print CFG "# This file is autogenerated by tools/create-shellconf.pl,\n";
print CFG "# using data from nms::config.\n";
print CFG "#\n";
print CFG "# Do you need new common/configuration variables?\n";
print CFG "# Add/update include/config.local.pm and tools/create-shellconf.pl\n\n";
print CFG "PRIMARY=\"$nms::config::pri_hostname.$nms::config::tgname.gathering.org\"\n";
print CFG "SECONDARY=\"$nms::config::sec_hostname.$nms::config::tgname.gathering.org\"\n";
print CFG "TGNAME=\"$nms::config::tgname\"\n\n";
print CFG "PRI_V4=\"$nms::config::pri_v4\"\n";
print CFG "PRI_V6=\"$nms::config::pri_v6\"\n";
print CFG "SEC_V4=\"$nms::config::sec_v4\"\n\n";
print CFG "SEC_V6=\"$nms::config::sec_v6\"\n\n";
close CFG;
