{
 "title": "TG19 Public",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "content": "<div style=\"height: 100%; margin-top: auto; margin-bottom: auto';\"><span style='text-align: center; margin-top: auto; margin-bottom: auto';><img src=\"https://stats.geekevents.org/tg16_logo.svg\" style=\"height: 100%; object-fit: contain; margin-top: auto; margin-bottom: auto';\" alt=\"TG-logo\"></span></div>"
  },
  {
   "title": "Ping Interwebz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "IPv4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "ipv4.ccnp.no" }
     ]
    },
    {
     "alias": "IPv6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "ipv6.ccnp.no" }
     ]
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 FROM \"ports\" WHERE (\"switch\" = 'nocgw' AND \"interface\" = 'xe-0/1/3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ports",
     "query": "SELECT mean(“value”) AS “traffic_in” FROM “interface.traffic” WHERE “host” = ‘MyHost’ AND “namecache” =~ /Traffic - 1/0/15/ AND “type” = ‘traffic_in’ AND timeFilter GROUP BY time(__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Total Upload",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ports",
     "query": "SELECT mean(“value”) AS “traffic_in” FROM “interface.traffic” WHERE “host” = ‘MyHost’ AND “namecache” =~ /Traffic - 1/0/15/ AND “type” = ‘traffic_in’ AND timeFilter GROUP BY time(__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Interwebz",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "DHCP v4 VS v6",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPv4",
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v4_used" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "IPv6",
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v6_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IPv4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v4_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "IPv6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v6_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active IPv4 Leases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPv4",
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v4_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total MAC's Seen",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "targets": [
    {
     "rawSql": "select count(distinct data->>'clientmac') from metrics;"
    }
   ]
  },
  {
   "title": "Active IPv6 Leases",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IPv4",
     "measurement": "dhcp-summary",
     "select": [
      [
       { "params": [ "v6_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique MAC's last 15m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 21 },
   "targets": [
    {
     "rawSql": "select count(distinct data->>'clientmac') from metrics WHERE time > NOW() - INTERVAL '15 minutes';"
    }
   ]
  },
  {
   "title": "WLC Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.stand" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "xe-0/0/5" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.stand" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "xe-2/0/5" }
     ]
    }
   ]
  },
  {
   "title": "Top Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_switch Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "40" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/^e.*/" }
     ]
    },
    {
     "alias": "$tag_switch Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "40" ], "type": "moving_average" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/^e.*/" }
     ]
    }
   ]
  },
  {
   "title": "Top Distro",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_switch Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "20" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/.*floor/" }
     ]
    },
    {
     "alias": "$tag_switch Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "20" ], "type": "moving_average" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/.*floor/" }
     ]
    }
   ]
  }
 ]
}