#!/usr/bin/perl -I /root/tgmanage/
use strict;
use warnings;

unless (@ARGV > 0) {
        print "No arguments. Need netlist.txt.\n";
        exit 1;
}

my $n = open(NETLIST, "$ARGV[0]") or die ("Cannot open netlist.txt");

print "# Autogenerated. Do not touch!\n";
print "package Config;\n";
print "our \@networks = (\n";

while(<NETLIST>) {
	next if /^(.*#|\s+$)/;  # skip if comment, or blank line

        chomp;
        my ($v4_net, $v6_net, $net_name) = split;

        print "\t\"$v4_net\",\n";
}

print ");\n";
print "1;\n";
