{
 "title": "TG23 Public",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"margin-top: auto; margin-bottom: auto';\"><span style='text-align: center; margin-top: auto; margin-bottom: auto';><img src=\"https://www.gathering.org/api/wp-content/uploads/2023/01/TG23GaiaLogo_logo.png\" style=\"object-fit: contain; margin-top: auto; margin-bottom: auto';\" alt=\"TG-logo\"></span></div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ping Gathering.org",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "gathering.org" }
     ]
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "query": "SELECT non_negative_derivative(mean(\"ifHCInOctets\"), 1s) *8 FROM \"ports\" WHERE (\"switch\" = 'nocgw' AND \"interface\" = 'xe-0/1/3') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Total Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ports",
     "query": "SELECT mean(“value”) AS “traffic_in” FROM “interface.traffic” WHERE “host” = ‘MyHost’ AND “namecache” =~ /Traffic - 1/0/15/ AND “type” = ‘traffic_in’ AND timeFilter GROUP BY time(__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Total Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ports",
     "query": "SELECT mean(“value”) AS “traffic_in” FROM “interface.traffic” WHERE “host” = ‘MyHost’ AND “namecache” =~ /Traffic - 1/0/15/ AND “type” = ‘traffic_in’ AND timeFilter GROUP BY time(__interval) fill(none)",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Interwebz",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "switch", "operator": "=", "value": "r1.tele" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "ae0" }
     ]
    }
   ]
  },
  {
   "title": "Active IPv4 Leases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "20s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kea_dhcp",
     "query": "SELECT sum(\"assigned-addresses\") FROM \"kea_dhcp\" WHERE (\"type\" = 'ipv4') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "assigned-addresses" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active IPv6 Leases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "IPv6",
     "groupBy": [
      { "params": [ "20s" ], "type": "time" }
     ],
     "measurement": "kea_dhcp",
     "query": "SELECT sum(\"assigned-nas\") FROM \"kea_dhcp\" WHERE (\"type\" = 'ipv6') AND $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "assigned-nas" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ipv6" }
     ]
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kea_dhcp",
     "query": "SELECT sum(\"assigned-addresses\") AS \"IPv4\", sum(\"assigned-nas\") as \"IPv6\" FROM \"kea_dhcp\" WHERE $timeFilter GROUP BY time(10s) fill(none)",
     "select": [
      [
       { "params": [ "assigned-addresses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ipv4" }
     ]
    }
   ]
  },
  {
   "title": "Top Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_switch Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "40" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/^e.*/" }
     ]
    },
    {
     "alias": "$tag_switch Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "40" ], "type": "moving_average" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/^e.*/" }
     ]
    }
   ]
  },
  {
   "title": "Top Distro",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_switch Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "20" ], "type": "moving_average" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/.*floor/" }
     ]
    },
    {
     "alias": "$tag_switch Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ports",
     "select": [
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "20" ], "type": "moving_average" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ae0" },
      { "condition": "AND", "key": "switch", "operator": "=~", "value": "/.*floor/" }
     ]
    }
   ]
  }
 ]
}