@template nms-base

FROM debian:jessie

ENV container docker
MAINTAINER "Kristian" <kly@kly.no>
#RUN systemctl set-default basic.target
RUN apt-get update && apt-get -y install	\
	 wget					\
	 vim					\
	 man					\
	 build-essential			\
	 net-tools				\
	 bash-completion			\
	 git-core				\
	 autoconf				\
	 netcat					\
	 libwww-perl				\
	 libmicrohttpd-dev			\
	 libcurl4-gnutls-dev			\
	 libedit-dev				\
	 libpcre3-dev				\
	 libncurses5-dev			\
	 python-demjson				\
	 python-docutils			\
	 libtool				\
	 nodejs					\
	 httpie					\
	 locales				\
	 screen					\
	 pkg-config	

VOLUME [ "/sys/fs/cgroup" ]
VOLUME [ "/run" ]
VOLUME [ "/run/lock" ]
RUN echo en_US.UTF8 UTF-8 > /etc/locale.gen
RUN locale-gen
RUN echo 'LANG="en_US.utf8"' > /etc/default/locale
RUN echo . /etc/default/locale >> /root/.bashrc
RUN echo export LANG >> /root/.bashrc
RUN echo . /etc/bash_completion >> /root/.bashrc
ENV TERM=rxvt-unicode
ADD .vimrc /root/.vimrc
RUN rm /etc/apt/apt.conf.d/docker-clean
RUN systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount systemd-logind.service
RUN git clone https://github.com/tech-server/tgmanage.git /srv/tgmanage
#RUN systemctl disable systemd-logind.service
CMD ["/sbin/init"]

@template nms-front
FROM nms-base
RUN apt-get -y install			\
	libcapture-tiny-perl		\
	libcgi-pm-perl			\
	libcommon-sense-perl		\
	libdata-dumper-simple-perl	\
	libdbd-pg-perl			\
	libdbi-perl			\
	libdigest-perl			\
	libgd-perl			\
	libgeo-ip-perl			\
	libhtml-parser-perl		\
	libhtml-template-perl		\
	libimage-magick-perl		\
	libimage-magick-q16-perl	\
	libjson-perl			\
	libjson-xs-perl			\
	libnetaddr-ip-perl		\
	libnet-cidr-perl		\
	libnet-ip-perl			\
	libnet-openssh-perl		\
	libnet-oping-perl		\
	libnet-rawip-perl		\
	libnet-telnet-cisco-perl	\
	libnet-telnet-perl		\
	libsnmp-perl			\
	libsocket6-perl			\
	libsocket-perl			\
	libswitch-perl			\
	libtimedate-perl		\
	perl				\
	perl-base			\
	perl-modules			\
	varnish				\
	apache2				\

RUN cd /srv/tgmanage/ && tools/get_mibs.sh

RUN sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
RUN a2dissite 000-default
RUN ln -s /srv/tgmanage/web/etc/apache2/nms.tg16.gathering.org.conf /etc/apache2/sites-enabled/

RUN systemctl enable apache2

RUN rm /etc/varnish/default.vcl
RUN ln -s /srv/tgmanage/web/etc/varnish/nms.vcl /etc/varnish/default.vcl
RUN sed -i 's/6081/80/' /lib/systemd/system/varnish.service
RUN echo 'demo:$apr1$IKrQYF6x$0zmRciLR7Clc2tEEosyHV.' > /srv/tgmanage/web/.htpasswd
RUN a2enmod cgi
RUN systemctl enable varnish


@template nms-db
FROM nms-base
RUN apt-get install -y postgresql-doc-9.4 postgresql-9.4

