# This file is autogenerated by tools/create-shellconf.pl,
# using data from nms::config.
#
# Do you need new common/configuration variables?
# Add/update include/config.local.pm and tools/create-shellconf.pl

PRIMARY="winix.tg13.gathering.org"
SECONDARY="tress90.tg13.gathering.org"
TGNAME="tg13"

PRI_PTR="151.216.126.2"
SEC_PTR="151.216.125.2"

DDNS_KEY="<removed>"

BASEV4="151.216.0.0"
PREFIXV4="17"
BASEV6="2a02:ed02:"
PREFIXV6="32"
